// Generated by https://quicktype.io

export interface CategoriesResposne {
    id:           number;
    Nombre:       string;
    Descripccion: string;
    created_at:   string;
    updated_at:   null;
}
