// Generated by https://quicktype.io

export interface ClientesResponse {
    id:         number;
    Nombre:     string;
    Telefono:   string;
    Email:      string;
    Password:   string;
    created_at: string;
    updated_at: null;
}
